# Setup
title:               David Dickson
tagline:             'personal blog'
description:         'Personal blog on technnology and related topics.'
url:                 https://www.davidkdickson.com
baseurl:             ''
permalink:           pretty

# About/contact
author:
  name:              David Dickson
  url:               https://twitter.com/davidkdickson

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-71269187-1
